apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/XwilberX/multitenant-demo.git
        revision: HEAD
        directories:
          - path: cluster-ops/tenants/*
          - path: cluster-ops/tenants/base
            exclude: true
  template:
    metadata:
      name: "tenant-{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/XwilberX/multitenant-demo.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "tenant-{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
